### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by lee-egist** [leahgoldberg/leahgoldberg.github.io#13]
In regards to your stereotype threat blog post I though it was well written and well thought out. There is a sentence that go: " I kept telling myself that I didn’t care and I wouldn’t his comments affect me" i think it is missing a "let".

as far as your leave a comment text boxes. there is no way to actually submit those comments. you are missing the <input type="submit" name="submit" value="Submit"> and also the comment field might me better as a <textarea col="50" row="10"> it could be cols and rows instead of col and row i'm not too sure on the syntax. but that way people can see everything they have typed. alternatively you could make a mailto: link <a href"mailto:your-email">

**Comment by leahgoldberg** [comment]
Thanks for catching that typo!

In terms of the comments section, I actually haven't done anything to update that yet -- it's still just a placeholder. I'm planning to work on that this week so that it actually functions -- I might try your mailto idea, since that sounds fairly simple!
