### ISSUE TITLE
Feedback on your website

### ISSUE THREAD

**Issue by RebeccaKleinberg** [leahgoldberg/leahgoldberg.github.io#3]
Hi Leah. This is our first time interacting, but I think you are my neighbor. First of all, I think your website is gorgeous. It's clean, readable, easy to navigate, and functional with live links and all! Have you done this before? I think your website is a great example for me to look at to see how HTML5 & CSS can be used to create a website that tells a story. I can't think of any critical feedback. It seems to match your aesthetic and gives a picture of who you are. I look forward to meeting & working with you. £:D Rk

**Comment by leahgoldberg** [comment]
Thanks so much, Rebecca - I've done a little bit with HTML/CSS before, but nothing too advanced, so always nice to hear the positive feedback! Looking forward to working with you soon too :)
