### ISSUE TITLE
Feedback for t3-arrays-hashes

### ISSUE THREAD

**Issue by kripple** [leahgoldberg/leahgoldberg.github.io#6]
Stuff I liked:
- Real world coffee example (so cool)
- Crazy coffee-making pic at bottom
- Clear, concise explanations

Potential Additions:
- Add some CSS to the links in your text body. Could make them the same color as your titles if you want to keep the blue.

**Comment by leahgoldberg** [comment]
Thanks for the feedback! I'll definitely add some CSS when I work on my blog this weekend. (Also, check out Pop Chart Labs for even more awesome charts!)
